DeviceProcessEvents
| where FileName =~ "net.exe" or FileName =~ "net1.exe"
| where ProcessCommandLine has "administrator"
| where (ProcessCommandLine has "P@ssw0rd!") or (ProcessCommandLine has "/active:yes" and ProcessCommandLine has "/dom")
| project TimeGenerated, DeviceName, AccountName, InitiatingProcessAccountName, FileName, ProcessCommandLine, InitiatingProcessFileName, InitiatingProcessCommandLine